### ISSUE TITLE
Sqlite structure is missing

### ISSUE THREAD

**Issue by matejdivecky** [agajdosi/unhuman-resources#23]
main.py is trying to use statistics module, which fails on request because of missing sqlite structure.

`access
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "main.py", line 36, in get
    page = await gen.with_timeout(time.time() + 30, getResponse(self))
  File "main.py", line 50, in getResponse
    statistics.countVisitor(self)
  File "/tmp/babis.media/unhuman-resources/statistics.py", line 10, in countVisitor
    cursor = conn.execute("INSERT INTO visitors (ip) VALUES ('{0}')".format(handler.request.remote_ip))
sqlite3.OperationalError: no such table: visitors
ERROR:tornado.access:500 GET / (::1) 2.53ms`

Rest of code works fine after commenting out statistics module from code, but this should be either done by default, or db structure should be provided in repo.

**Comment by agajdosi** [comment]
Hi @matejdivecky, I am sorry for late reply. Missed the mail from GH... Thank you for the bug report. DB was a leftover of old statistics solution which was later replaced by tags for google statistics.

I have removed the statistics module and its usage in from the code base in https://github.com/agajdosi/unhuman-resources/commit/bf01375e5c42303bf44f0550cf690c02fa246965. I will try to provide a flag for custom google tags asap (right now tags are hardcoded).
